config/routes.rb
Piggylet::Application.routes.draw do
  resources :piggybanks

end

app/models/piggybank.rb
class Piggybank < ActiveRecord::Base
  attr_accessible :name, :penny, :nickle, :dime, :quarter, :dollar

  def total_cents
    penny.to_i + nickle.to_i*5 + dime.to_i*10 + quarter.to_i*25 + dollar.to_i*100
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/piggybanks_controller.rb
class PiggybanksController < ApplicationController
  def index
    @piggybanks = Piggybank.all
  end

  def show
    @piggybank = Piggybank.find(params[:id])
  end

  def new
    @piggybank = Piggybank.new
  end

  def create
    @piggybank = Piggybank.create(params[:piggybank])
    @piggybank.save
    redirect_to piggybanks_path
  end

  def edit
    @piggybank = Piggybank.find(params[:id])
  end

  def update
    @piggybank = Piggybank.find(params[:id])
    @piggybank.update_attributes(params[:piggybank])
    @piggybank.save
    redirect_to edit_piggybank_path(@piggybank)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Piggylet</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/piggybanks/edit.html.erb
<div style="float: left;">
  <%= form_for @piggybank do |f| %>
    <%= @piggybank.name %>
    <br />
    <%= f.label :penny %>
    <%= f.text_field :penny %>
    <br />
    <%= f.label :nickle %>
    <%= f.text_field :nickle %>
    <br />
    <%= f.label :dime %>
    <%= f.text_field :dime %>
    <br />
    <%= f.label :quarter %>
    <%= f.text_field :quarter %>
    <br />
    <%= f.label :dollar %>
    <%= f.text_field :dollar %>
    <br />
    <%= f.submit%>
  <% end %>
</div>
<div style="float: left;">
  <div>
    Coin / Number / Cents
  </div>
  <div>
    Pennies /
    <%= @piggybank.penny %> /
    <%= @piggybank.penny.to_i %>
  </div>
  <div>
    Nickle /
    <%= @piggybank.nickle %> /
    <%= @piggybank.nickle.to_i*5 %>
  </div>
  <div>
    Dime /
    <%= @piggybank.dime %> /
    <%= @piggybank.dime.to_i*10 %>
  </div>
  <div>
    Quarter /
    <%= @piggybank.quarter %> /
    <%= @piggybank.quarter.to_i*25 %>
  </div>
  <div>
    Dollar /
    <%= @piggybank.dollar %> /
    <%= @piggybank.dollar.to_i*100 %>
  </div>
  <div>
    Total / /
    <%= @piggybank.total_cents %>
  </div>
</div>

app/views/piggybanks/index.html.erb
<% @piggybanks.each do |piggybank| %>
  <%= link_to "Edit #{piggybank.name}", edit_piggybank_path(piggybank) %>
  <%= link_to "View #{piggybank.name}", piggybank_path(piggybank) %>
  <br />
<% end %>
<%= link_to "Create New", new_piggybank_path %>

app/views/piggybanks/new.html.erb
<div>
  <%= form_for @piggybank do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit%>
  <% end %>
</div>
    

app/views/piggybanks/show.html.erb
<div>
  <%= @piggybank.name %>
</div>
<div>
  Total Amount:
  <%= @piggybank.total_cents %>
</div>
<div>
  Convert to:
  <%= form_tag url: piggybank_path(@piggybank), method: :get do %>
    <br />
    <%= radio_button_tag :coin, "pennies" %>
    Pennies
    <br />
    <%= radio_button_tag :coin, "nickles" %>
    Nickles
    <%= submit_tag :coin %>
  <% end %>
</div>